# Generated by Django 4.2.7 on 2025-11-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account ID for OAuth', max_length=255, null=True, unique=True),
        ),
    ]
