# Generated by Django 4.2.7 on 2025-11-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_date_of_birth_enrollment_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='verification_id',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
