# Generated by Django 4.2.7 on 2025-11-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollmentapplication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentapplication',
            old_name='course_levels',
            new_name='levels',
        ),
        migrations.RemoveField(
            model_name='enrollmentapplication',
            name='verification_id_file',
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Upload ID proof (PDF, Image, or Document)', null=True, upload_to='verification_documents/'),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload your signature image', null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('payment_pending', 'Payment Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
