# Generated by Django 4.2.7 on 2025-11-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_certificate_approved_by_certificate_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload your photo', null=True, upload_to='student_photos/'),
        ),
    ]
