# Generated by Django 4.2.7 on 2025-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrollmentapplication_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='preferred_hour',
            field=models.CharField(blank=True, help_text='Preferred hour for weekday classes (e.g., "9:00 AM", "2:00 PM")', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('weekday', 'Weekday (1 hour)'), ('weekend', 'Weekend (2 hours)')], help_text='Preferred schedule type', max_length=10),
        ),
    ]
